### ISSUE TITLE
Support of new testnets

### ISSUE THREAD

**Issue by dansentivany** [input-output-hk/cardano-db-sync#1238]
Since the old testnet was dropped, preview and preprod should be supported now? Is there a way to make them work in the current published docker image?

**Comment by AdamMachera** [comment]
yes, we need this

**Comment by netog-ppb** [comment]
is there any workaround or guide on how to use the new config files with the cardano-db-sync docker image?

**Comment by AdamMachera** [comment]
sudo groupadd docker
sudo usermod -aG docker $USER
newgrp docker 

sudo apt-get update 
Update docker compose: https://phoenixnap.com/kb/install-docker-compose-on-ubuntu-20-04
sudo apt-get install docker.io

sudo mkdir /datadrive
sudo chgrp docker  /datadrive/
sudo chmod g+w /datadrive/

docker volume create node-db
docker volume create node-ipc
docker volume create node-config

mkdir /datadrive/node-db
mkdir /datadrive/node-ipc
mkdir /datadrive/node-config

download config files from:
https://book.world.dev.cardano.org/environments/preprod/
to /datadrive/node-config

sudo rm -rf /var/lib/docker/volumes/node-db/_data
sudo rm -rf /var/lib/docker/volumes/node-ipc/_data
sudo rm -rf /var/lib/docker/volumes/node-config/_data

sudo ln -s /datadrive/node-db /var/lib/docker/volumes/node-db/_data 
sudo ln -s /datadrive/node-ipc /var/lib/docker/volumes/node-ipc/_data 
sudo ln -s /datadrive/node-config /var/lib/docker/volumes/node-config/_data 


modify docker-compose.yaml
docker-compose.yaml



services:
  cardano-node:
    image: inputoutput/cardano-node:1.35.3
    volumes:
      - node-db:/data/db
      - node-ipc:/ipc
      - node-config:/config
    command:
      - run
      - --config /config/config.json
      - --topology /config/topology.json
      - --database-path /data/db
      - --socket-path /ipc/node.socket
    restart: on-failure
    healthcheck:
      # Ping the EKG port to see if it responds.
      # Assuming if EKG isn't up then the rest of cardano-node isn't either.
      test: ["CMD-SHELL", "curl -f 127.0.0.1:12788 || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  node-db:
    external: true
  node-ipc:
    external: true
  node-config:
    external: true


execute:
docker-compose up

**Comment by cardano-tools-nft** [comment]
for node we have already 1.35.3-configs and can set network to preview, but cardano-db-sync:13.0.4 tells 

Managed configuration for network preview does not exist

when trying preview as network

**Comment by glneto** [comment]
Here you also have a db-sync-config file: https://book.world.dev.cardano.org/environments/preview/

I was able to run cardano-db-sync in preview network by updating the docker-compose.yml file. Remove the NETWORK from environment and add `command` along with config and socket path arguments.

```
environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - RESTORE_SNAPSHOT=${RESTORE_SNAPSHOT:-}
      - RESTORE_RECREATE_DB=N
    command:
      - --config /config/db-sync-config.json
      - --socket-path /node-ipc/node.socket
```

**Comment by cardano-tools-nft** [comment]
Thanks seems to work:

1. downloaded

- alonzo-genesis.json
- byron-genesis.json
- config.json
- db-sync-config.json
- shelley-genesis.json

from https://book.world.dev.cardano.org/environments.html#preview-testnet

put them into folder  ./config/preview at docker-compose file

use this compose config:

```
  cardano-node:
    image: inputoutput/cardano-node:1.35.3-configs
    environment:
      - NETWORK=preview
    volumes:
      - node-db:/data/db
      - node-ipc:/ipc
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cardano-db-sync:
    image: inputoutput/cardano-db-sync:13.0.4
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - RESTORE_SNAPSHOT=${RESTORE_SNAPSHOT:-}
      #- RESTORE_SNAPSHOT=https://updates-cardano-testnet.s3.amazonaws.com/cardano-db-sync/13/db-sync-snapshot-schema-13-block-3680594-x86_64.tgz
      - RESTORE_RECREATE_DB=N
    depends_on:
      - cardano-node
      - postgres
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    command: --config /config/db-sync-config.json --socket-path /node-ipc/node.socket
    volumes:
      - db-sync-data:/var/lib/cexplorer
      - node-ipc:/node-ipc
      - ./tmp:/tmp
      - ./config/preview:/config
      - ./config/preview:/genesis
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
```
