### ISSUE TITLE
Unable to find datum for transaction

### ISSUE THREAD

**Issue by Displee** [input-output-hk/cardano-db-sync#1321]
**OS**
Your OS: Debian 11

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 13.0.4
PostgreSQL version: 11.5-alpine

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: docker-compose

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): Docker

**Additional context**
docker-compose.yml
```yml
version: "3.5"

services:
  postgres:
    image: postgres:11.5-alpine
    shm_size: 2gb
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cardano-node:
    image: inputoutput/cardano-node:1.35.3-configs
    environment:
      - NETWORK=${NETWORK:-mainnet}
    volumes:
      - node-db:/data/db
      - node-ipc:/ipc
      - ./projects:/projects
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cardano-db-sync:
    image: inputoutput/cardano-db-sync:13.0.4
    environment:
      - NETWORK=${NETWORK:-mainnet}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - RESTORE_SNAPSHOT=${RESTORE_SNAPSHOT:-}
      - RESTORE_RECREATE_DB=N
    depends_on:
      - cardano-node
      - postgres
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - db-sync-data:/var/lib/cexplorer
      - node-ipc:/node-ipc
      - ./snapshots:/snapshots
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cardano-wallet:
    image: inputoutput/cardano-wallet:2022.8.16
    volumes:
      - wallet-${NETWORK}-db:/wallet-db
      - node-ipc:/ipc
    expose:
      - "8090"
    entrypoint: []
    command: bash -c "
        ([[ $$NETWORK == \"mainnet\" ]] && $$CMD --mainnet) ||
        ($$CMD --testnet /config/${NETWORK}/genesis-byron.json)
      "
    environment:
      CMD: "cardano-wallet serve --node-socket /ipc/node.socket --database /wallet-db --listen-address 0.0.0.0"
      NETWORK:
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
    networks:
      - proxy

secrets:
  postgres_db:
    file: ./config/secrets/postgres_db
  postgres_password:
    file: ./config/secrets/postgres_password
  postgres_user:
    file: ./config/secrets/postgres_user

volumes:
  db-sync-data:
  postgres:
  node-db:
  node-ipc:
  wallet-mainnet-db:

networks:
  proxy:
    external: true
```

**Problem Report**
I'm a little puzzled with a transaction which gives different results in different tools. I'm trying to find the datum for the transaction with hash: `034cd38f3f8387e6963c78175e459a2ffab0e36becb36510aaa81534f6ea6e54`

For this, I execute the following Postgres query:
```postgres
SELECT * FROM datum WHERE tx_id = (SELECT id from tx WHERE hash = '\x034cd38f3f8387e6963c78175e459a2ffab0e36becb36510aaa81534f6ea6e54')
```
My db sync returns no results. Then I tried to use GraphQL with [Dandelion's API](https://graphql-api.mainnet.dandelion.link/) using the query:
```graphql
{
    transactions(
        where: { hash: { _eq: "034cd38f3f8387e6963c78175e459a2ffab0e36becb36510aaa81534f6ea6e54" } }
    ) {
    		redeemers {
          datum {
            
            hash,
            bytes,
            value
          }
        }
    }
}
```
This returned the following:
```graphql
{
  "data": {
    "transactions": [
      {
        "redeemers": [
          {
            "datum": {
              "hash": "8392f0c940435c06888f9bdb8c74a95dc69f156367d6a089cf008ae05caae01e",
              "bytes": "d87a80",
              "value": {
                "fields": [],
                "constructor": 1
              }
            }
          }
        ]
      }
    ]
  }
}
```
As you can see there is a datum linked to it. However, the datum hash doesn't seem to match the one from cardanoscan:
https://cardanoscan.io/transaction/034cd38f3f8387e6963c78175e459a2ffab0e36becb36510aaa81534f6ea6e54?tab=contracts

I then tried using the Blockfrost's API and sent the request:
```
https://cardano-mainnet.blockfrost.io/api/v0/txs/034cd38f3f8387e6963c78175e459a2ffab0e36becb36510aaa81534f6ea6e54/redeemers
```
Which returned the same datum hash as the one I got from GraphQL:
```json
[
    {
        "tx_index": 0,
        "purpose": "spend",
        "script_hash": "ec26b89af41bef0f7585353831cb5da42b5b37185e0c8a526143b824",
        "redeemer_data_hash": "923918e403bf43c34b4ef6b48eb2ee04babed17320d8d1b9ff9ad086e86f44ec",
        "datum_hash": "923918e403bf43c34b4ef6b48eb2ee04babed17320d8d1b9ff9ad086e86f44ec",
        "unit_mem": "1700",
        "unit_steps": "476468",
        "fee": "172033"
    }
]
```
I have threequestions.
1. Which datum hash is correct?
2. Why does cardano db sync not return the associated datum with the query above?
3. Why does cardanoscan return a different datum than GraphQL or Blockfrost?
