### ISSUE TITLE
Preview network starting epoch has unusual dates and duration resulting in <100% sync

### ISSUE THREAD

**Issue by mikemorency** [input-output-hk/cardano-db-sync#1395]
**OS**
Ubuntu

**Versions**
inputoutput/cardano-node:1.35.4
inputoutput/cardano-db-sync:13.1.0.0
postgres:11.18-alpine

**Build/Install Method**
Docker Hub

**Run method**
docker compose
```
version: "3.9"

services:
  postgres:
    image: postgres:11.18-alpine
    environment:
      - POSTGRES_LOGGING=true
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - blockfrost

  cardano-node:
    image: inputoutput/cardano-node:1.35.4
    environment:
      - NETWORK=${NETWORK:-preview}
    ports:
      - 3001:3001
    volumes:
      - node-db:/data
      - node-ipc:/ipc
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -f 127.0.0.1:12788 || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - blockfrost

  cardano-db-sync:
    image: inputoutput/cardano-db-sync:13.1.0.0
    environment:
      - NETWORK=${NETWORK:-preview}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - RESTORE_SNAPSHOT=${RESTORE_SNAPSHOT:-}
      - RESTORE_RECREATE_DB=N
      - EXTRA_DB_SYNC_ARGS=${EXTRA_DB_SYNC_ARGS:-}
    ports:
      - 3002:3002
    depends_on:
      cardano-node:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - db-sync-data:/var/lib/cexplorer
      - node-ipc:/node-ipc
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - blockfrost

  blockfrost:
    image: blockfrost/backend-ryo:latest
    environment:
      - BLOCKFROST_CONFIG_DBSYNC_HOST=postgres
      - BLOCKFROST_CONFIG_SERVER_LISTEN_ADDRESS=0.0.0.0
      - NODE_APP_INSTANCE=development
      - BLOCKFROST_CONFIG_DBSYNC_USER=${DB_USER}
      - BLOCKFROST_CONFIG_DBSYNC_DATABASE=${DB_NAME}
      - PGPASSWORD=${DB_PASSWORD}
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config:/app/config
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - blockfrost

volumes:
  db-sync-data:
  postgres:
  node-db:
  node-ipc:

networks:
  blockfrost:
    name: custom_blockfrost_net
```

**Additional context**
I am using the docker-compose above to run these services locally. I used the cloud provided instance of https://blockfrost.io/ to validate the results of the local instances.
Ive tested this same configuration with preprod and production. They are not affected by this and achieve 100% sync rates

**Problem Report**
When using the preview network configuration contained in the cardano-* docker image, the starting epoch is different than the starting epoch shown by the cloud instance of Blockfrost. The duration of the epoch is also different.
This seems to cause the docker instances to never reach 100% in sync (measured by running the PSQL query to check in-sync percentage) and the dates of the most recent epoch are off. The cardano-db-sync logging shows that it is at the tip of the chain and keeping up with cardano-node, and no error messages are logged.

Below is starting epoch values from the docker hosted instances:
```
>>: curl http://localhost:3000/epochs/0
{"epoch":0,"start_time":1660003200,"end_time":1660435200,"first_block_time":1660003200,"last_block_time":1660089580,"block_count":4320,"tx_count":2,"output":"59999998493362207","fees":"437793","active_stake":null}
```

And this is the same endpoint on the cloud hosted solution:
`{"epoch":0,"start_time":1666656000,"end_time":1666742400,"first_block_time":1666656000,"last_block_time":1666742380,"block_count":4320,"tx_count":2,"output":"59999998493362207","fees":"437793","active_stake":null}`
