### ISSUE TITLE
Wrong block size

### ISSUE THREAD

**Issue by infnada** [input-output-hk/cardano-db-sync#1451]
**OS**
Your OS:

**Versions**
The `db-sync` version: 13.1.1.2
PostgreSQL version: 15.3

**Build/Install Method**
inputoutput/cardano-db-sync:13.1.1.2-docker

**Run method**
Docker

**Additional context**
Snapshot: 13.1/db-sync-snapshot-schema-13.1-block-8883740-x86_64.tgz

```
  cardano-db-sync:
    image: inputoutput/cardano-db-sync:13.1.1.2-docker
    environment:
      - NETWORK=${NETWORK:-mainnet}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - RESTORE_SNAPSHOT=${RESTORE_SNAPSHOT:-https://update-cardano-mainnet.iohk.io/cardano-db-sync/13.1/db-sync-snapshot-schema-13.1-block-8883740-x86_64.tgz}
      - RESTORE_RECREATE_DB=N
      - EXTRA_DB_SYNC_ARGS=--consumed-tx-out
```

**Problem Report**
All blocks after 8883740 (last of loaded snapshot) contain a wrong block size. Don't know if its because incompatible PSQL version or db-sync issue.

```
SELECT block_no, time, size FROM block WHERE block_no > 8883735 LIMIT 10
```
| block_no | time                      | size  |
|----------|---------------------------|-------|
| 8883736  | 2023-06-09 21:59:39.000000 | 87327 |
| 8883737  | 2023-06-09 21:59:48.000000 | 81026 |
| 8883738  | 2023-06-09 22:00:04.000000 | 87564 |
| 8883739  | 2023-06-09 22:00:24.000000 | 82681 |
| 8883740  | 2023-06-09 22:00:31.000000 | 88046 |
| 8883741  | 2023-06-09 22:02:38.000000 |   862 |
| 8883742  | 2023-06-09 22:02:51.000000 |   861 |
| 8883743  | 2023-06-09 22:03:38.000000 |   861 |
| 8883744  | 2023-06-09 22:03:47.000000 |   861 |
| 8883745  | 2023-06-09 22:03:58.000000 |   861 |

```
SELECT DISTINCT ON (size) size, block_no, time FROM block WHERE block_no > 8883735
```
|  size     | block_no | time                      |
|---------|-----------|---------------------------|
| 857      | 8900808 | 2023-06-13 23:57:42.000000 |
| 858      | 8900756 | 2023-06-13 23:42:41.000000 |
| 859      | 8902968 | 2023-06-14 12:21:37.000000 |
| 860      | 8947720 | 2023-06-25 05:36:31.000000 |
| 861      | 8954598 | 2023-06-26 22:02:48.000000 |
| 862      | 8901147 | 2023-06-14 01:57:47.000000 |
| 863      | 8898702 | 2023-06-13 11:50:32.000000 |
| 865      | 8933454 | 2023-06-21 17:58:11.000000 |
| 81026    | 8883737 | 2023-06-09 21:59:48.000000 |
| 82681    | 8883739 | 2023-06-09 22:00:24.000000 |
| 87327    | 8883736 | 2023-06-09 21:59:39.000000 |
| 87564    | 8883738 | 2023-06-09 22:00:04.000000 |
| 88046    | 8883740 | 2023-06-09 22:00:31.000000 |

```
SELECT MAX(block_no) FROM block

8960666
```

Randomly they get a size from 857 to 865 (excluding 864 for some reason)
