### ISSUE TITLE
Error: insertValidateGenesisDist: Genesis data mismatch.

### ISSUE THREAD

**Issue by islishude** [input-output-hk/cardano-db-sync#206]
vesion: 3.0.0 by docker

```yaml
version: "3.5"

services:
  node:
    image: inputoutput/cardano-node:master
    environment:
      - NETWORK=mainnet_candidate_4
    volumes:
      - /data/ada-shelley-testnet/chaindata:/data/db
      - /data/ada-shelley-testnet/socket:/ipc
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"

  dbsync:
    image: inputoutput/cardano-db-sync:3.0.0
    environment:
      - EXTENDED=true
      - NETWORK=mainnet_candidate_4
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - node
      - postgres
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - /data/ada-shelley-testnet/socket:/node-ipc
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
```
