### ISSUE TITLE
when NETWORK=testnet docker-compose up, I think it has different genesis.json

### ISSUE THREAD

**Issue by sjlee1125** [input-output-hk/cardano-db-sync#220]
here is my docker-compose.yaml
```
version: "3.5"

services:
  postgres:
    image: postgres:11.5-alpine
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"

  cardano-node:
    image: inputoutput/cardano-node:${CARDANO_NODE_VERSION:-1.18.0}
    environment:
      - NETWORK=${NETWORK:-mainnet}
    volumes:
      - node-db:/data/db
      - node-ipc:/ipc
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cardano-db-sync:
    image: inputoutput/cardano-db-sync:${CARDANO_DB_SYNC_VERSION:-3.0.0}
    environment:
      - NETWORK=${NETWORK:-mainnet}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - cardano-node
      - postgres
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - node-ipc:/node-ipc
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cardano-submit-api:
    image: inputoutput/cardano-submit-api:${CARDANO_SUBMIT_API_VERSION:-2.1.0}
    environment:
      - NETWORK=${NETWORK:-mainnet}
    depends_on:
      - cardano-node
    volumes:
      - node-ipc:/node-ipc
    ports:
      - 8101:8101
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

secrets:
  postgres_db:
    file: ./config/postgres_db
  postgres_password:
    file: ./config/postgres_password
  postgres_user:
    file: ./config/postgres_user

volumes:
  postgres:
  node-db:
  node-ipc:
```

cardano-node version is 1.18.0 and   cardano-db-sync version is 3.0.0
I think it's default testnet genesis.json file is different from cardano-node's

```
NETWORK=testnet docker-compose up
```
after this i got error 

```
cardano-db-sync_1     | With Cardano protocol, Byron/Shelley config mismatch:
cardano-db-sync_1     |    SystemStart 2019-07-24 20:20:16 UTC /= 2019-07-22 20:20:16 UTC
```
How can i  find solution?
