### ISSUE TITLE
Change to PG credential configuration

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-db-sync#26]
To improve service provisioning, it would be helpful to separate the credentials from the current `pgpass` file, as demonstrated in the following docker-compose snippet:

``` yaml
services:
  cardano-db-sync:
    ...
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
  postgres:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
secrets:
  postgres_db:
    file: ./config/secrets/postgres_db
  postgres_password:
    file: ./config/secrets/postgres_password
  postgres_user:
    file: ./config/secrets/postgres_user
```

_N.B. This pattern should not be seen as specific to Docker, but it does provide Docker with a secure way of managing sensitive information._

## Proposed changes
1. Read values **directly** from ENVs (not sensitive):
- `POSTGRES_HOST`
- `POSTGRES_PORT`
2. Read string from **files** nominated by the following ENVs:
- `POSTGRES_DB_FILE`
- `POSTGRES_PASSWORD_FILE`
- `POSTGRES_USER_FILE`
3. To reduce complexity, refactor fall-though to align with this granular handling instead of a `pgpass`, setting the ENVs if not found on service init.
