### ISSUE TITLE
Missing testnet config files. Downloading online files doesn't help. Please comment.

### ISSUE THREAD

**Issue by TinFury** [input-output-hk/cardano-db-sync#592]
Having a problem running the default setup for cardano-db-sync. testnet.yaml is missing so I used
shelley-qa-testnet.yaml 

PGPASSFILE=config/pgpass-testnet db-sync-node/bin/cardano-db-sync \
    --config ./config/shelley-qa-testnet.yaml \
    --socket-path ../cardano-node/state-node-testnet/node.socket \
    --state-dir ledger-state/testnet \
    --schema-dir schema/

File below referes to indented files
-------------------------------------------------
shelley-qa-testnet.yaml 
-qshelley_qa-config.json
--shelley_qa-byron-genesis.json
--shelley_qa-shelley-genesis.json

shelley_qa-byron-genesis.json - Should protocolMagic be 3?
Line 61 - , "protocolConsts": { "k": 36, "protocolMagic": 3 }

shelley_qa-shelley-genesis.json - Should networkMagic be 1097911063???
Line 45 - "networkMagic": 3,

Changing these numbers generates hash mismatch error. I am guessing that it is the hash reference from qshelley_qa-config.json below.

  "ByronGenesisHash": "9325495d3ac7554d4bfaf2392cc3c74676d5add873d6ef8862d7562e660940bf",
  "ShelleyGenesisHash": "85d1783750753deaa6560158eb85fcb30078ea32a36e12dd8af39168bc053d09",

How do I regenerate the hash for these files once I've changed "protocolMagic" and "networkMagic"? Am I even doing the right thing?
Why are the config files missing and the downloadable ones not configured right? Is anyone using Cardano for anything?

**Comment by TinFury** [comment]
Am I missing something? Where is everyone?

**Comment by erikd** [comment]
You raised this on Saturday and Monday was a public holiday where I live. You will usually not get immediate responses, especially not on weekend and public holidays.

If you are trying to set these in `db-sync` you are doing it the wrong way. You seem to be so deep down some rabbit hole that I cannot even figure out what you are trying to do.

First question is why are you trying to run the "shelley-qa" network?

**Comment by TinFury** [comment]
First thank you for your reply.

What is the shelly-qa network? It it not mentioned on this page https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/building-running.md. I am trying to connect to the testnet.

For the node. testnet-node-local uses this config. So I am assuming /nix/store/rzbxsb0dnya58pwp1j1fnypsn8rn5s6z-config-0.json

xec /nix/store/yja7bx8xyyv15nch148bcilygh9sabyp-cardano-node-exe-cardano-node-1.26.1/bin/cardano-node run --config /nix/store/rzbxsb0dnya58pwp1j1fnypsn8rn5s6z-config-0.json --database-path state-node-testnet/db-testnet --topology /nix/store/dpajyi2vaychwps1x7d20c2ddls4kf62-topology.yaml --host-addr 127.0.0.1 --port 3001 --socket-path state-node-testnet/node.socket      +RTS -N2 -A16m -qg -qb --disable-delayed-os-memory-return -RTS $@

**Comment by TinFury** [comment]
I was trying to use shelly-qa network because in the example --config config/testnet-config.yaml does not exist. I tried to use shelly  and also tried to use /nix/store/rzbxsb0dnya58pwp1j1fnypsn8rn5s6z-config-0.json.

**Comment by TinFury** [comment]
This is what fixed it all in the end for anyone else having the problem. Thanks Priyank on Telegram.

https://hydra.iohk.io/build/5821110/download/1/index.html

Used that config file and within it pointed it to the node config file used by testnet-node-local.

**Comment by TinFury** [comment]
Thank you too erikd.

**Comment by ggcaponetto** [comment]
I am running into the same problem. I downloaded the config (renamed to db-sync-testnet-config.yml) from [here](https://hydra.iohk.io/build/5821110/download/1/index.html) for the testnet and i try to pass its path int the docker compose file like this:

```
version: "3.5"

services:
  postgres:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cardano-node:
    image: inputoutput/cardano-node:1.26.2
    volumes:
      - node-db:/data/db
      - node-ipc:/node-ipc
      - ./node-config:/node-config
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    command: [
      "run",
      "--topology /node-config/testnet/testnet-topology.json",
      "--config /node-config/testnet/testnet-config.json",
      "--socket-path /node-ipc/node.socket",
      "--database-path /data/db"
    ]
  cardano-db-sync:
    image: inputoutput/cardano-db-sync:9.0.0
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - cardano-node
      - postgres
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - db-sync-data:/var/lib/cdbsync
      - node-ipc:/node-ipc
      - state-dir:/state-dir
      - ./node-config:/node-config
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    command: [
        "--config /node-config/testnet/db-sync-testnet-config.yml",
        "--socket-path /node-ipc/node.socket",
        "--state-dir /state-dir"
    ]
secrets:
  postgres_db:
    file: ./cardano-db-sync/config/secrets/postgres_db
  postgres_password:
    file: ./cardano-db-sync/config/secrets/postgres_password
  postgres_user:
    file: ./cardano-db-sync/config/secrets/postgres_user
volumes:
  db-sync-data:
  postgres:
  node-db:
  node-ipc:
  node-config:
  state-dir:

```

but when i run it cardano-db-sync exits with the following error:

```
cardano-db-sync_1  | /run/secrets
cardano-db-sync_1  | Generating PGPASS file
postgres_1         | syncing data to disk ...
cardano-db-sync_1  | Connecting to network specified in configuration.yaml
postgres_1         | WARNING: enabling "trust" authentication for local connections
cardano-db-sync_1  | cardano-db-sync: FatalError {fatalErrorMessage = "Cannot find the node configuration file at : /nix/store/j9zxdffwvxl3q4m5rfrk86ips92fxd3y-config-testnet.json"}
```

I wish there was an explicit documentation to help users bootstrap the testnet with docker. If i only knew how, I would contribute to the docs!

Thanks everybody for the support!
