### ISSUE TITLE
Can't connect to the testnet

### ISSUE THREAD

**Issue by ggcaponetto** [input-output-hk/cardano-db-sync#628]
Hello! I am trying to run the testnet via docker. Unfortunately i can't figure out how so i tried the following approach.
I checked out the tag 9.0.0 and updated the image cardano-node to version1.26.2.
Then I downloaded the config (renamed to db-sync-testnet-config.yml) from [here](https://hydra.iohk.io/build/5821110/download/1/index.html) for the testnet and I try to pass its path in the docker compose ``service.command`` as stated in the [docs - take control](https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/docker.md).

My compose file is this:

```
version: "3.5"

services:
  postgres:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cardano-node:
    image: inputoutput/cardano-node:1.26.2
    volumes:
      - node-db:/data/db
      - node-ipc:/node-ipc
      - ./node-config:/node-config
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    command: [
      "run",
      "--topology /node-config/testnet/testnet-topology.json",
      "--config /node-config/testnet/testnet-config.json",
      "--socket-path /node-ipc/node.socket",
      "--database-path /data/db"
    ]
  cardano-db-sync:
    image: inputoutput/cardano-db-sync:9.0.0
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - cardano-node
      - postgres
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - db-sync-data:/var/lib/cdbsync
      - node-ipc:/node-ipc
      - state-dir:/state-dir
      - ./node-config:/node-config
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    command: [
        "--config /node-config/testnet/db-sync-testnet-config.yml",
        "--socket-path /node-ipc/node.socket",
        "--state-dir /state-dir"
    ]
secrets:
  postgres_db:
    file: ./cardano-db-sync/config/secrets/postgres_db
  postgres_password:
    file: ./cardano-db-sync/config/secrets/postgres_password
  postgres_user:
    file: ./cardano-db-sync/config/secrets/postgres_user
volumes:
  db-sync-data:
  postgres:
  node-db:
  node-ipc:
  node-config:
  state-dir:

```

When i run it cardano-db-sync exits (code 1) with the following error:

```
cardano-db-sync_1  | /run/secrets
cardano-db-sync_1  | Generating PGPASS file
postgres_1         | syncing data to disk ...
cardano-db-sync_1  | Connecting to network specified in configuration.yaml
postgres_1         | WARNING: enabling "trust" authentication for local connections
cardano-db-sync_1  | cardano-db-sync: FatalError {fatalErrorMessage = "Cannot find the node configuration file at : /nix/store/j9zxdffwvxl3q4m5rfrk86ips92fxd3y-config-testnet.json"}
```

It looks like it not finding or pointing to the correct configuration. I wish there was an explicit documentation to help users bootstrap the testnet with docker. If i only knew how, I would contribute to the docs!

Thanks everybody for the support!
