### ISSUE TITLE
State Snapshot restore script fails

### ISSUE THREAD

**Issue by ggcaponetto** [input-output-hk/cardano-db-sync#861]
**OS**
Ubuntu focal

**Versions**
11.0.3

**Build/Install Method**
docker-compose running the following services:
- postgres:11.5-alpine
- inputoutput/cardano-node:1.30.1 (bind mound for directory `/state-dir`)
- inputoutput/cardano-db-sync:11.0.3 (bind mound for directory `/state-dir`)

The sync runs fine.

**Problem Report**
I stop the cardano-db-sync service first as described in the documentation.
Then I try to restore the ledger state from the snapshot provided in version 11.0.3 for the mainnet.

I am running the command
``PGPASSFILE=/root/cardano-db-snapshot/pgpass bash /root/cardano-db-snapshot/postgresql-setup.sh --restore-snapshot /root/cardano-db-snapshot/db-sync-snapshot-schema-9-block-5796064-x86_64 /root/code/141x/setup/cardano-db-sync/state-dir``

and getting the error

``ERROR:  cannot drop objects owned by role postgres because they are required by the database system``

**Additional  Context**
My pgpassfile: ``localhost:5432:cexplorer:postgres:<mypass>`` 

Maybe I am doing something wrong but I am stuck on this and would appreciate some help.

**Comment by erikd** [comment]
> ERROR: cannot drop objects owned by role postgres because they are required by the database system

It looks like you have another process access the database at the same time you are trying to restore the database. Postgres says no.

This is not a `db-sync` issue.

**Comment by ggcaponetto** [comment]
Thank you very much @erikd.

**Comment by ggcaponetto** [comment]
Turns out I am supposed to restore the db snapshot in another way if I use docker-compose.

@rhyslbw @jbgi To my understanding the [commit](https://github.com/input-output-hk/cardano-db-sync/commit/637f4e5cc202b15166a5b68132f796e5f1ad8a49#diff-f326740d6904dcd8395de479c104f66febdb6e9076fc428265f25b6207c08c72) should make it possible to start the cardano-db-sync and perform a snapshot restore using the environment variables `RESTORE_SNAPSHOT` and `RESTORE_SNAPSHOT` but it's not officially documented [here](https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/state-snapshot.md) and I am not sure if I am doing it correctly.

My docker compose is standard and looks like this:
```
version: "3.5"

x-141x-node-config:
  &141x-node-config
  type: bind
  source: ./node-config
  target: /node-config
x-141x-node-ipc:
  &141x-node-ipc
  type: bind
  source: ./node-ipc
  target: /node-ipc
x-141x-state-dir:
  &141x-state-dir
  type: bind
  source: ./state-dir
  target: /state-dir

services:
  postgres:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: on-failure
  cardano-node:
    image: inputoutput/cardano-node:1.30.1
    volumes:
      - <<: *141x-node-config
      - <<: *141x-node-ipc
      - <<: *141x-state-dir
      - node-db:/data/db
    restart: on-failure
    command: [
    "run",
    "--topology /node-config/mainnet/mainnet-topology.json",
    "--config /node-config/mainnet/mainnet-config.json",
    "--socket-path /node-ipc/node.socket",
    "--database-path /data/db"
    ]
  cardano-db-sync:
    image: inputoutput/cardano-db-sync:11.0.3
    env_file:
      - mainnet.env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - DB_SYNC_NETWORK=${DB_SYNC_NETWORK}
      - NETWORK=${DB_SYNC_NETWORK}
      - PGPASSFILE=/node-config/${DB_SYNC_NETWORK}/pgpass
      - CARDANO_NODE_SOCKET_PATH=/node-ipc
      - RESTORE_SNAPSHOT=/root/cardano-db-snapshot/db-sync-snapshot-schema-11-block-6278640-x86_64.tgz
      - RESTORE_RECREATE_DB=Y
    depends_on:
      - cardano-node
      - postgres
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - <<: *141x-node-config
      - <<: *141x-node-ipc
      - <<: *141x-state-dir
      - db-sync-data:/var/lib/cdbsync
    restart: on-failure
secrets:
  postgres_db:
    file: ./cardano-db-sync/config/secrets/postgres_db
  postgres_password:
    file: ./cardano-db-sync/config/secrets/postgres_password
  postgres_user:
    file: ./cardano-db-sync/config/secrets/postgres_user
volumes:
  db-sync-data:
  postgres:
  node-db:
  schema:
networks:
  default:
    name: 141x
    driver: bridge

```
after starting the compse file i get the following error:

```
cardano-node_1     | [739d59bd:cardano.node.ChainDB:Notice:35] [2021-09-30 17:47:48.35 UTC] Chain extended, new tip: b775d4d9a1fa88ac3de790bcc515b55994c3a04c10ddf893d1f2242a6135b4c3 at slot 257440
cardano-node_1     | [739d59bd:cardano.node.ChainDB:Notice:35] [2021-09-30 17:47:48.82 UTC] Chain extended, new tip: 71275d3a2bfa27b54c3ad036ab90a78e2b524d3de9882f15b92d7148bd9bb9b6 at slot 257602
cardano-node_1     | [739d59bd:cardano.node.ChainDB:Notice:35] [2021-09-30 17:47:50.08 UTC] Chain extended, new tip: 4b72449da9fdbc04eca22d8285e8bb6ec94373e52278be617439501381a35677 at slot 258178
cardano-node_1     | [739d59bd:cardano.node.ChainDB:Notice:35] [2021-09-30 17:47:51.33 UTC] Chain extended, new tip: 0d9270a71358185b0ad5e3507690d4600239c20e767bf5d361ffc31821615b83 at slot 258757
cardano-db-sync_1  | ERROR:  cannot drop objects owned by role postgres because they are required by the database system
postgres_1         | 2021-09-30 17:47:51.951 UTC [82] ERROR:  cannot drop objects owned by role postgres because they are required by the database system
postgres_1         | 2021-09-30 17:47:51.951 UTC [82] STATEMENT:  DROP OWNED BY CURRENT_USER;
cardano-db-sync_cardano-db-sync_1 exited with code 1
```
Is there something more I can try?
